spring.application.name=employee-service
# Service poort uit de opdracht
server.port=8081

# Database configuratie (eigen schema per service volgens vereiste 05)
spring.datasource.url=jdbc:mysql://localhost:3307/employee_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Zorgt dat de tabellen automatisch worden aangemaakt
spring.jpa.hibernate.ddl-auto=update