spring.application.name=organization-service

# Poort volgens de opdrachteisen
server.port=8083

# Eigen schema (department_db) via de Docker container op poort 3307
spring.datasource.url=jdbc:mysql://localhost:3307/organization_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
